name: Build and run functional tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - develop
      - develop-sync
  pull_request:

jobs:
  functional_tests:
    name: Run tests
    uses: ./.github/workflows/functional_tests.yml
